# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/04751832-5ed2-40ad-88ca-3758f684a072";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4373-64EF";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/srv/backup" = {
    device = "/dev/disk/by-uuid/77ea5d69-8ad6-4c9d-8cb4-cf70bf9c6d19";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  # fileSystems."/srv/temp" = {
  #   device = "/dev/disk/by-uuid/776D-C5F6";
  #   fsType = "exfat";
  #   options = [ "noatime" ];
  # };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6a3e3cc2-95c9-47c2-b95c-8e73bcf3d624"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
