# Theme
# include mocha.conf
include custom.conf

# Transparency
background_opacity 0.85

# Font
font_family IBM Plex Mono
font_size 10.0

# Cursor
cursor_shape beam

# Padding
window_padding_width 8

hide_window_decorations yes

wayland_titlebar_color background

confirm_quit no

confirm_os_window_close 0

cursor_trail 3
